### PR TITLE
Initial interfaces

### PR DESCRIPTION
**Pull request by mecha**
**Work in Progress**

### CODE REVIEW

**Review by XedinUnknown — COMMENTED** [review]
Do you think it would make sense to have e.g. `EntityAwareInterface#getEntity(): string|Stringable`?

**Comment by mecha** [comment]
Do you mean instead of [`EntityNameAwareInterface#getEntityName()`](https://github.com/Dhii/sql-interface/blob/task/initial-interfaces/src/EntityNameAwareInterface.php#L21)?

**Comment by XedinUnknown** [comment]
Nope.

**Comment by XedinUnknown** [comment]
Yeap.

**Comment by XedinUnknown** [comment]
@mecha, add branch alias please.

**Comment by XedinUnknown** [comment]
@mecha,. build failed for PHP 5.3 due to wrong `dhii/php-cs-fixer-config` version.

**Pull request merged**
